export interface User {
    id: number,
    email: string,
    password: string,
    firstName: string,
    lastName: string,
    brand: string,
    area: string,
    phone: number,
    gender: string,
    type: string,
    name: string,
    address: string,
    creditCard: string,
    creditCardCVV: string,
    subscription: string,
}
